#pragma once

#include <map>
#include <string>

namespace vsql_addr_std
{

static const std::map<std::string, std::string> directional{
    {"N", "N"},   {"NORTH", "N"},      {"S", "S"},   {"SOUTH", "S"},      {"E", "E"},   {"EAST", "E"},
    {"W", "W"},   {"WEST", "W"},       {"NE", "NE"}, {"NORTHEAST", "NE"}, {"NW", "NW"}, {"NORTHWEST", "NW"},
    {"SE", "SE"}, {"SOUTHEAST", "SE"}, {"SW", "SW"}, {"SOUTHWEST", "SW"},
};

static const std::unordered_map<std::string, std::string> secondary_addr{
    {"APARTMENT", "APT"}, {"APT", "APT"},         {"BASEMENT", "BSMT"}, {"BSMT", "BSMT"}, {"BUILDING", "BLDG"},
    {"BLDG", "BLDG"},     {"DEPARTMENT", "DEPT"}, {"DEPT", "DEPT"},     {"FLOOR", "FL"},  {"FL", "FL"},
    {"FRONT", "FRNT"},    {"FRNT", "FRNT"},       {"HANGAR", "HNGR"},   {"HNGR", "HNGR"}, {"LOBBY", "LBBY"},
    {"LBBY", "LBBY"},     {"LOT", "LOT"},         {"LOWER", "LOWR"},    {"LOWR", "LOWR"}, {"OFFICE", "OFC"},
    {"OFC", "OFC"},       {"PENTHOUSE", "PH"},    {"PH", "PH"},         {"PIER", "PIER"}, {"REAR", "REAR"},
    {"ROOM", "RM"},       {"RM", "RM"},           {"SIDE", "SIDE"},     {"SLIP", "SLIP"}, {"SPACE", "SPC"},
    {"SPC", "SPC"},       {"STOP", "STOP"},       {"SUITE", "STE"},     {"STE", "STE"},   {"TRAILER", "TRLR"},
    {"TRLR", "TRLR"},     {"UNIT", "UNIT"},       {"UPPER", "UPPR"},    {"UPPR", "UPPR"}, {"#", "#"},
};

static const std::map<std::string, std::string> suffix_map = {
    {"ALLEE", "ALY"},       {"ALLEY", "ALY"},       {"ALLY", "ALY"},      {"ALY", "ALY"},        {"ANEX", "ANX"},
    {"ANX", "ANX"},         {"ARC", "ARC"},         {"ARCADE", "ARC"},    {"AV", "AVE"},         {"AVE", "AVE"},
    {"AVEN", "AVE"},        {"AVENU", "AVE"},       {"AVENUE", "AVE"},    {"AVN", "AVE"},        {"AVNUE", "AVE"},
    {"BAYOO", "BYU"},       {"BAYOU", "BYU"},       {"BYU", "BYU"},       {"BCH", "BCH"},        {"BEACH", "BCH"},
    {"BEND", "BND"},        {"BND", "BND"},         {"BLF", "BLF"},       {"BLUF", "BLF"},       {"BLUFF", "BLF"},
    {"BLUFFS", "BLFS"},     {"BLFS", "BLFS"},       {"BOT", "BTM"},       {"BTM", "BTM"},        {"BOTTM", "BTM"},
    {"BOTTOM", "BTM"},      {"BLVD", "BLVD"},       {"BOUL", "BLVD"},     {"BOULEVARD", "BLVD"}, {"BOULV", "BLVD"},
    {"BR", "BR"},           {"BRANCH", "BR"},       {"BRNCH", "BR"},      {"BRDGE", "BRG"},      {"BRG", "BRG"},
    {"BRIDGE", "BRG"},      {"BRK", "BRK"},         {"BROOK", "BRK"},     {"BROOKS", "BRKS"},    {"BRKS", "BRKS"},
    {"BG", "BG"},           {"BURG", "BG"},         {"BURGS", "BGS"},     {"BGS", "BGS"},        {"BYP", "BYP"},
    {"BYPA", "BYP"},        {"BYPAS", "BYP"},       {"BYPASS", "BYP"},    {"BYPS", "BYP"},       {"CAMP", "CP"},
    {"CP", "CP"},           {"CMP", "CP"},          {"CANYN", "CYN"},     {"CANYON", "CYN"},     {"CNYN", "CYN"},
    {"CYN", "CYN"},         {"CAPE", "CPE"},        {"CPE", "CPE"},       {"CAUSEWAY", "CSWY"},  {"CAUSWA", "CSWY"},
    {"CSWY", "CSWY"},       {"CEN", "CTR"},         {"CENT", "CTR"},      {"CENTER", "CTR"},     {"CENTR", "CTR"},
    {"CENTRE", "CTR"},      {"CNTER", "CTR"},       {"CNTR", "CTR"},      {"CTR", "CTR"},        {"CENTERS", "CTRS"},
    {"CTRS", "CTRS"},       {"CIR", "CIR"},         {"CIRC", "CIR"},      {"CIRCL", "CIR"},      {"CIRCLE", "CIR"},
    {"CRCL", "CIR"},        {"CRCLE", "CIR"},       {"CIRCLES", "CIRS"},  {"CIRS", "CIRS"},      {"CLF", "CLF"},
    {"CLIFF", "CLF"},       {"CLFS", "CLFS"},       {"CLIFFS", "CLFS"},   {"CLB", "CLB"},        {"CLUB", "CLB"},
    {"COMMON", "CMN"},      {"CMN", "CMN"},         {"COMMONS", "CMNS"},  {"CMNS", "CMNS"},      {"COR", "COR"},
    {"CORNER", "COR"},      {"CORNERS", "CORS"},    {"CORS", "CORS"},     {"COURSE", "CRSE"},    {"CRSE", "CRSE"},
    {"COURT", "CT"},        {"CT", "CT"},           {"COURTS", "CTS"},    {"CTS", "CTS"},        {"COVE", "CV"},
    {"CV", "CV"},           {"COVES", "CVS"},       {"CVS", "CVS"},       {"CREEK", "CRK"},      {"CRK", "CRK"},
    {"CRESCENT", "CRES"},   {"CRES", "CRES"},       {"CRSENT", "CRES"},   {"CRSNT", "CRES"},     {"CREST", "CRST"},
    {"CRST", "CRST"},       {"CROSSING", "XING"},   {"CRSSNG", "XING"},   {"XING", "XING"},      {"CROSSROAD", "XRD"},
    {"XRD", "XRD"},         {"CURVE", "CURV"},      {"CURV", "CURV"},     {"DALE", "DL"},        {"DL", "DL"},
    {"DAM", "DM"},          {"DM", "DM"},           {"DIV", "DV"},        {"DIVIDE", "DV"},      {"DV", "DV"},
    {"DVD", "DV"},          {"DR", "DR"},           {"DRIV", "DR"},       {"DRIVE", "DR"},       {"DRV", "DR"},
    {"DRIVES", "DRS"},      {"DRS", "DRS"},         {"EST", "EST"},       {"ESTATE", "EST"},     {"ESTATES", "ESTS"},
    {"ESTS", "ESTS"},       {"EXP", "EXPY"},        {"EXPR", "EXPY"},     {"EXPRESS", "EXPY"},   {"EXPRESSWAY", "EXPY"},
    {"EXPW", "EXPY"},       {"EXPY", "EXPY"},       {"EXT", "EXT"},       {"EXTENSION", "EXT"},  {"EXTN", "EXT"},
    {"FALL", "FALL"},       {"FALLS", "FLS"},       {"FLS", "FLS"},       {"FERRY", "FRY"},      {"FRRY", "FRY"},
    {"FRY", "FRY"},         {"FIELD", "FLD"},       {"FLD", "FLD"},       {"FIELDS", "FLDS"},    {"FLDS", "FLDS"},
    {"FLAT", "FLT"},        {"FLT", "FLT"},         {"FLATS", "FLTS"},    {"FLTS", "FLTS"},      {"FORD", "FRD"},
    {"FRD", "FRD"},         {"FOREST", "FRST"},     {"FRST", "FRST"},     {"FORG", "FRG"},       {"FORGE", "FRG"},
    {"FRG", "FRG"},         {"FORK", "FRK"},        {"FRK", "FRK"},       {"FORKS", "FRKS"},     {"FRKS", "FRKS"},
    {"FORT", "FT"},         {"FRT", "FT"},          {"FT", "FT"},         {"FREEWAY", "FWY"},    {"FRWAY", "FWY"},
    {"FWY", "FWY"},         {"GARDEN", "GDN"},      {"GDN", "GDN"},       {"GARDENS", "GDNS"},   {"GDNS", "GDNS"},
    {"GATEWAY", "GTWY"},    {"GTWY", "GTWY"},       {"GLEN", "GLN"},      {"GLN", "GLN"},        {"GREEN", "GRN"},
    {"GRN", "GRN"},         {"GROVE", "GRV"},       {"GRV", "GRV"},       {"HARBOR", "HBR"},     {"HBR", "HBR"},
    {"HAVEN", "HVN"},       {"HVN", "HVN"},         {"HEIGHTS", "HTS"},   {"HTS", "HTS"},        {"HIGHWAY", "HWY"},
    {"HIWAY", "HWY"},       {"HWY", "HWY"},         {"HILL", "HL"},       {"HL", "HL"},          {"HILLS", "HLS"},
    {"HLS", "HLS"},         {"HOLLOW", "HOLW"},     {"HOLW", "HOLW"},     {"INLET", "INLT"},     {"INLT", "INLT"},
    {"IS", "IS"},           {"ISLAND", "IS"},       {"ISLANDS", "ISS"},   {"ISS", "ISS"},        {"JCT", "JCT"},
    {"JUNCTION", "JCT"},    {"JCTN", "JCT"},        {"KEY", "KY"},        {"KY", "KY"},          {"KNL", "KNL"},
    {"KNOLL", "KNL"},       {"KNLS", "KNLS"},       {"KNOLLS", "KNLS"},   {"LK", "LK"},          {"LAKE", "LK"},
    {"LKS", "LKS"},         {"LAKES", "LKS"},       {"LAND", "LAND"},     {"LANDING", "LNDG"},   {"LNDG", "LNDG"},
    {"LANE", "LN"},         {"LN", "LN"},           {"LGT", "LGT"},       {"LIGHT", "LGT"},      {"LF", "LF"},
    {"LOAF", "LF"},         {"LCK", "LCK"},         {"LOCK", "LCK"},      {"LDG", "LDG"},        {"LODGE", "LDG"},
    {"LOOP", "LOOP"},       {"MALL", "MALL"},       {"MNR", "MNR"},       {"MANOR", "MNR"},      {"MDW", "MDW"},
    {"MEADOW", "MDW"},      {"MDWS", "MDWS"},       {"MEADOWS", "MDWS"},  {"MEWS", "MEWS"},      {"ML", "ML"},
    {"MILL", "ML"},         {"MLS", "MLS"},         {"MILLS", "MLS"},     {"MSN", "MSN"},        {"MISSION", "MSN"},
    {"MTWY", "MTWY"},       {"MOTORWAY", "MTWY"},   {"MT", "MT"},         {"MOUNT", "MT"},       {"MTN", "MTN"},
    {"MOUNTAIN", "MTN"},    {"NCK", "NCK"},         {"NECK", "NCK"},      {"ORCH", "ORCH"},      {"ORCHARD", "ORCH"},
    {"OVAL", "OVAL"},       {"OPAS", "OPAS"},       {"OVERPASS", "OPAS"}, {"PARK", "PARK"},      {"PARKS", "PARK"},
    {"PARKWAY", "PKWY"},    {"PKWY", "PKWY"},       {"PKY", "PKWY"},      {"PASS", "PASS"},      {"PASSAGE", "PSGE"},
    {"PSGE", "PSGE"},       {"PATH", "PATH"},       {"PIKE", "PIKE"},     {"PNE", "PNE"},        {"PINE", "PNE"},
    {"PNES", "PNES"},       {"PINES", "PNES"},      {"PL", "PL"},         {"PLACE", "PL"},       {"PLAIN", "PLN"},
    {"PLN", "PLN"},         {"PLAINS", "PLNS"},     {"PLNS", "PLNS"},     {"PLAZA", "PLZ"},      {"PLZ", "PLZ"},
    {"PT", "PT"},           {"POINT", "PT"},        {"PTS", "PTS"},       {"POINTS", "PTS"},     {"PRT", "PRT"},
    {"PORT", "PRT"},        {"PR", "PR"},           {"PRAIRIE", "PR"},    {"RADL", "RADL"},      {"RADIAL", "RADL"},
    {"RNCH", "RNCH"},       {"RANCH", "RNCH"},      {"RPD", "RPD"},       {"RAPID", "RPD"},      {"RST", "RST"},
    {"REST", "RST"},        {"RDG", "RDG"},         {"RIDGE", "RDG"},     {"RDGS", "RDGS"},      {"RIDGES", "RDGS"},
    {"RIV", "RIV"},         {"RIVER", "RIV"},       {"RD", "RD"},         {"ROAD", "RD"},        {"RDS", "RDS"},
    {"ROADS", "RDS"},       {"RTE", "RTE"},         {"ROUTE", "RTE"},     {"ROW", "ROW"},        {"RUE", "RUE"},
    {"RUN", "RUN"},         {"SHL", "SHL"},         {"SHOAL", "SHL"},     {"SHR", "SHR"},        {"SHORE", "SHR"},
    {"SPG", "SPG"},         {"SPRING", "SPG"},      {"SPGS", "SPGS"},     {"SPRINGS", "SPGS"},   {"SPUR", "SPUR"},
    {"SQ", "SQ"},           {"SQUARE", "SQ"},       {"STA", "STA"},       {"STATION", "STA"},    {"STRA", "STRA"},
    {"STRAVENUE", "STRA"},  {"STRM", "STRM"},       {"STREAM", "STRM"},   {"ST", "ST"},          {"STR", "ST"},
    {"STREET", "ST"},       {"STRT", "ST"},         {"STS", "STS"},       {"STREETS", "STS"},    {"SMT", "SMT"},
    {"SUMMIT", "SMT"},      {"TER", "TER"},         {"TERR", "TER"},      {"TERRACE", "TER"},    {"TRWY", "TRWY"},
    {"THROUGHWAY", "TRWY"}, {"TRCE", "TRCE"},       {"TRACE", "TRCE"},    {"TRAK", "TRAK"},      {"TRACK", "TRAK"},
    {"TRFY", "TRFY"},       {"TRAFFICWAY", "TRFY"}, {"TRL", "TRL"},       {"TRAIL", "TRL"},      {"TUNL", "TUNL"},
    {"TUNNEL", "TUNL"},     {"TPKE", "TPKE"},       {"TURNPIKE", "TPKE"}, {"UPAS", "UPAS"},      {"UNDERPASS", "UPAS"},
    {"UN", "UN"},           {"UNION", "UN"},        {"VLY", "VLY"},       {"VALLEY", "VLY"},     {"VIA", "VIA"},
    {"VIADUCT", "VIA"},     {"VW", "VW"},           {"VIEW", "VW"},       {"VLG", "VLG"},        {"VILLAGE", "VLG"},
    {"VL", "VL"},           {"VILLE", "VL"},        {"VIS", "VIS"},       {"VISTA", "VIS"},      {"WALK", "WALK"},
    {"WALL", "WALL"},       {"WAY", "WAY"},         {"WY", "WAY"},        {"WL", "WL"},          {"WELL", "WL"},
    {"WLS", "WLS"},         {"WELLS", "WLS"},
};

static const std::map<std::string, std::string> state_abbv = {
    {"ALABAMA", "AL"},
    {"AL", "AL"},
    {"ALASKA", "AK"},
    {"AK", "AK"},
    {"ARIZONA", "AZ"},
    {"AZ", "AZ"},
    {"ARKANSAS", "AR"},
    {"AR", "AR"},
    {"CALIFORNIA", "CA"},
    {"CA", "CA"},
    {"COLORADO", "CO"},
    {"CO", "CO"},
    {"CONNECTICUT", "CT"},
    {"CT", "CT"},
    {"DELAWARE", "DE"},
    {"DE", "DE"},
    {"FLORIDA", "FL"},
    {"FL", "FL"},
    {"GEORGIA", "GA"},
    {"GA", "GA"},
    {"HAWAII", "HI"},
    {"HI", "HI"},
    {"IDAHO", "ID"},
    {"ID", "ID"},
    {"ILLINOIS", "IL"},
    {"IL", "IL"},
    {"INDIANA", "IN"},
    {"IN", "IN"},
    {"IOWA", "IA"},
    {"IA", "IA"},
    {"KANSAS", "KS"},
    {"KS", "KS"},
    {"KENTUCKY", "KY"},
    {"KY", "KY"},
    {"LOUISIANA", "LA"},
    {"LA", "LA"},
    {"MAINE", "ME"},
    {"ME", "ME"},
    {"MARYLAND", "MD"},
    {"MD", "MD"},
    {"MASSACHUSETTS", "MA"},
    {"MA", "MA"},
    {"MICHIGAN", "MI"},
    {"MI", "MI"},
    {"MINNESOTA", "MN"},
    {"MN", "MN"},
    {"MISSISSIPPI", "MS"},
    {"MS", "MS"},
    {"MISSOURI", "MO"},
    {"MO", "MO"},
    {"MONTANA", "MT"},
    {"MT", "MT"},
    {"NEBRASKA", "NE"},
    {"NE", "NE"},
    {"NEVADA", "NV"},
    {"NV", "NV"},
    {"NEW HAMPSHIRE", "NH"},
    {"NH", "NH"},
    {"NEW JERSEY", "NJ"},
    {"NJ", "NJ"},
    {"NEW MEXICO", "NM"},
    {"NM", "NM"},
    {"NEW YORK", "NY"},
    {"NY", "NY"},
    {"NORTH CAROLINA", "NC"},
    {"NC", "NC"},
    {"NORTH DAKOTA", "ND"},
    {"ND", "ND"},
    {"OHIO", "OH"},
    {"OH", "OH"},
    {"OKLAHOMA", "OK"},
    {"OK", "OK"},
    {"OREGON", "OR"},
    {"OR", "OR"},
    {"PENNSYLVANIA", "PA"},
    {"PA", "PA"},
    {"RHODE ISLAND", "RI"},
    {"RI", "RI"},
    {"SOUTH CAROLINA", "SC"},
    {"SC", "SC"},
    {"SOUTH DAKOTA", "SD"},
    {"SD", "SD"},
    {"TENNESSEE", "TN"},
    {"TN", "TN"},
    {"TEXAS", "TX"},
    {"TX", "TX"},
    {"UTAH", "UT"},
    {"UT", "UT"},
    {"VERMONT", "VT"},
    {"VT", "VT"},
    {"VIRGINIA", "VA"},
    {"VA", "VA"},
    {"WASHINGTON", "WA"},
    {"WA", "WA"},
    {"WEST VIRGINIA", "WV"},
    {"WV", "WV"},
    {"WISCONSIN", "WI"},
    {"WI", "WI"},
    {"WYOMING", "WY"},
    {"WY", "WY"},
    {"DISTRICT OF COLUMBIA", "DC"},
    {"DC", "DC"},
    {"PUERTO RICO", "PR"},
    {"PR", "PR"},
    {"GUAM", "GU"},
    {"GU", "GU"},
    {"VIRGIN ISLANDS", "VI"},
    {"VI", "VI"},
    {"AMERICAN SAMOA", "AS"},
    {"AS", "AS"},
    {"NORTHERN MARIANA ISLANDS", "MP"},
    {"MP", "MP"},
};

} // namespace vsql_addr_std
